-- MySQL Script generated by MySQL Workbench
-- Mon Dec 16 19:45:42 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema LittleLemonDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema LittleLemonDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `LittleLemonDB` DEFAULT CHARACTER SET utf8 ;
USE `LittleLemonDB` ;

-- -----------------------------------------------------
-- Table `LittleLemonDB`.`Staff Information`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LittleLemonDB`.`Staff Information` (
  `Staff ID` INT NOT NULL,
  `Role` VARCHAR(45) NOT NULL,
  `Salary` DECIMAL NULL,
  PRIMARY KEY (`Staff ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LittleLemonDB`.`Bookings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LittleLemonDB`.`Bookings` (
  `Booking ID` INT NOT NULL,
  `Date` DATE NOT NULL,
  `Table Number` INT NOT NULL,
  `Staff ID` INT NOT NULL,
  PRIMARY KEY (`Booking ID`),
  INDEX `Staff ID_idx` (`Staff ID` ASC) VISIBLE,
  CONSTRAINT `Staff ID`
    FOREIGN KEY (`Staff ID`)
    REFERENCES `LittleLemonDB`.`Staff Information` (`Staff ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LittleLemonDB`.`Menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LittleLemonDB`.`Menu` (
  `Menu ID` INT NOT NULL,
  `Cuisines` VARCHAR(45) NULL,
  `Starters` VARCHAR(45) NULL,
  `Courses` VARCHAR(45) NULL,
  `Drinks` VARCHAR(45) NULL,
  `Desserts` VARCHAR(45) NULL,
  PRIMARY KEY (`Menu ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LittleLemonDB`.`Order Delivery Status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LittleLemonDB`.`Order Delivery Status` (
  `Status ID` INT NOT NULL,
  `Delivery Date` DATE NOT NULL,
  `Status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Status ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LittleLemonDB`.`Orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LittleLemonDB`.`Orders` (
  `Order ID` INT NOT NULL,
  `Order Date` DATE NOT NULL,
  `Quantity` INT NOT NULL,
  `Total Cost` DECIMAL NOT NULL,
  `Menu ID` INT NOT NULL,
  `Status ID` INT NOT NULL,
  PRIMARY KEY (`Order ID`),
  INDEX `Menu ID_idx` (`Menu ID` ASC) VISIBLE,
  INDEX `Status ID_idx` (`Status ID` ASC) VISIBLE,
  CONSTRAINT `Menu ID`
    FOREIGN KEY (`Menu ID`)
    REFERENCES `LittleLemonDB`.`Menu` (`Menu ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Status ID`
    FOREIGN KEY (`Status ID`)
    REFERENCES `LittleLemonDB`.`Order Delivery Status` (`Status ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LittleLemonDB`.`Customer Details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LittleLemonDB`.`Customer Details` (
  `Customer ID` INT NOT NULL,
  `Customer Names` VARCHAR(45) NOT NULL,
  `Contact Details` VARCHAR(45) NOT NULL,
  `Booking ID` INT NOT NULL,
  `Order ID` INT NOT NULL,
  PRIMARY KEY (`Customer ID`),
  INDEX `Booking ID_idx` (`Booking ID` ASC) VISIBLE,
  INDEX `Order ID_idx` (`Order ID` ASC) VISIBLE,
  CONSTRAINT `Booking ID`
    FOREIGN KEY (`Booking ID`)
    REFERENCES `LittleLemonDB`.`Bookings` (`Booking ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Order ID`
    FOREIGN KEY (`Order ID`)
    REFERENCES `LittleLemonDB`.`Orders` (`Order ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
